### ISSUE TITLE
Make Plugin() a Pimple Container?

### ISSUE THREAD

**Issue by GaryJones** [GaryJones/plugin-boilerplate#1]
I think I've convinced myself, but would like a second opinion please @Giuseppe-Mazzapica, @Rarst.

Please compare master and develop branches. The diff is [here](f3b66b3d1adbe1a30008f698e1708035a121aec7).  Both branches work in terms of echoing out the debug statements at the right places.  I want to have `Plugin` just responsible for adding in the WP hooks from the rest of the plugin via a `setup_hooks()` (or `run()`) method.

The original `master` branch kept `Plugin` and the Pimple Container instance separate, but that would mean having to pass each object over to the Plugin constructor so that `setup_hooks()` could reference it.

The `develop` makes Plugin extend the Pimple Container, and that means `setup_hooks()` can access all objects that are service providers, via `$this['foo']`.

Does the develop branch seem like the more sensible approach here?
Any potential gotchas to watch out for that my basic setup doesn't yet cover?

Thanks.

Ref: http://gm.zoomlab.it/2014/structured-applications-with-pimple/

**Comment by gmazzap** [comment]
>  I want to have Plugin just responsible for adding in the WP hooks from the rest of the plugin via a setup_hooks() (or run()) method.

I would not be surprised if me and Andrey have a different opinion on this. BTW, this is the mine.

Please don't do that. Don't create any `Plugin` class. You don't need that. Reason [here](http://wordpress.stackexchange.com/questions/70055/best-way-to-initiate-a-class-in-a-wp-plugin/166532#166532).

**Comment by Rarst** [comment]
Yeah, I am still fine with the approach at my evolution stage. :)

**Comment by GaryJones** [comment]
@Giuseppe-Mazzapica: So you'd have hooks relevant to each object inside their own `setup()` method?
How and when would you call that for each object?

Let's take a FrontEnd class. Doesn't your approach tie in _how_ that front-end element is rendered, with _when_ it is rendered?

With the approach I've got in develop, where Plugin is _only_ for hooking everything together rather than a god class for everything, I'd be trying to keep all the event-driven stuff in one place.

**Comment by gmazzap** [comment]
@GaryJones to build a WordPress plugin you need a _main_ plugin file. Is there any benefit on leave that file empty?

It isn't the absolutely first place where _everyone_ trying to understand your plugin will look at?

So, why don't use that file to add all the hooks? They will be all in one place, and in a place everyone can easily see them.

Also, if any -relevant- class has its own `setup()` method, someone using your plugin has an easier life replacing any of the classes, without touching the main Plugin class that adds all the hooks.

**Comment by GaryJones** [comment]
So global function calls in the main plugin file to:

``` php
add_action( 'some_hook', array( $container['foo'], 'bar' ) );
```

Got it.

Thoughts on https://github.com/tmf/wp-hookable-service/blob/master/classes/class-hookable-service-provider.php ?

**Comment by gmazzap** [comment]
Yep, more or less. I usually use a function to easily get container instance everywhere.

E.g.

``` php
namespace GM;

function getContainer() {
    static $container = NULL;
    if ( is_null( $container ) ) {
        $container = new Container;
        do_action('pluginname_container_ready', $container);
    }
    return $container;
}
```

Regarding service provider you linked:
- from a first read, seems there is no possibility to pass other services to service constructor, so DI is fucked up
- not sure having a service provider for any object is right thing to do

If I had to write Brain again today, the service provider would be just an interface like:

``` php
<?php namespace GM;

use Pimple\ServiceProviderInterface;
use Pimple\Container;

interface BootableServiceProviderInterface extends ServiceProviderInterface
{
    public function boot(Container $container);
}
```

And I also would add a function like that:

``` php
namespace GM;

use Pimple\Container;

function bootProviders($id, Container $container, array $providers = []) {

    array_walk($providers, function ($class) use ($container) {
        $provider = class_exists($class) ? new $class() : false;
        if ($provider instanceof ServiceProvider) {
            $container->register($provider);
        }
        $container['boot_queue'] = new \SplQueue();
        if ($provider instanceof BootableServiceProvider) {
            $container['boot_queue']->enqueue($provider);
        }
    });

     while (!$container->isEmpty()) {
        $container->dequeue()->boot($container); // boot any bootable provider
     }

     do_action('pluginname_providers_done', $id);
}
```

Doing so, any plugin can setup their providers as needed.

E.g. a typical provider would be:

``` php
namespace GM;

use Pimple\Container;

class BarServiceProvider implements BootableServiceProviderInterface
{
    public function register(Container $container)
    {
        $container['foo'] = function ($c) {
            return new Foo();
        };
        $container['bar'] = function ($c) {
            return new Bar($c['foo']);
        };
    }

    public function boot(Container $container)
    {
       $container['bar']->setup();
    }
}
```

Finally in main plugin file:

``` php
add_action('plugins_loaded', 'GM\getContainer');

// the hook is fired by getContainer() see above in this page
add_action('pluginname_container_ready', function($container) {

    add_action('init', function() use($container) {
        $providers = [
             'GM\Some\Core\FooProvider',
             'GM\Some\Core\BarProvider'
         ];
         GM\bootProviders( 'core', $providers, $container);    
    }, 30);

    add_action('admin_init', function()  use($container) {
        $admin_providers = [
             'GM\Some\Admin\FooProvider',
             'GM\Some\Admin\BarProvider'
         ];
         GM\bootProviders('admin', $providers, $container);
    }, 30);

});
```

What happen inside the `boot()` method of any service provider can be changed accordingly to plugin needs...

**Comment by gmazzap** [comment]
Also note how using `'pluginname_container_ready'` hook users can register their own service providers, extending your plugin.

Using `'pluginname_providers_done'` they can retrieve Container with `getContainer() and edit services being sure they are available.

**Comment by GaryJones** [comment]
That's a lot for me to take in and understand, so thank you in advance :-)

**Comment by GaryJones** [comment]
@Giuseppe-Mazzapica How does https://github.com/brightnucleus/testbed/blob/master/src/Plugin.php fare, in your opinion? cc @schlessera

**Comment by gmazzap** [comment]
@GaryJones good, and I wish the average WP code would be like that...

There are a few flaws that, sometimes, I had in my own code as well...

### Dangerous `get_instance` param

``` php
public static function get_instance( ConfigInterface $config = null ) {
    if ( ! self::$instance ) {
        self::$instance = new self( $config );
    }
    return self::$instance;
}
```

Here the `ConfigInterface` param is a bit dangerous. Reason is that if `get_instance` is called more than once with different configurations, all configurations but first are ignored.

So a piece of code like:

``` php
$instance = Testbed::get_instance($someConfig);
```

let you reasonably imagine that the `$someConfig` is used to configure the obtained instance. 
Which might be not true if `Testbed::get_instance` was called previously somewhere with a different configuration.

Consider that the plugin could be used as a dependency via composer by different and unrelated pieces of code that call `get_instance` with different arguments, and only the first will "win".

I honestly don't even know what the plugin does :) but, generally speaking, this is not an ideal design.

Not sure how it fits for the library, but throwing an exception if `get_instance` is called more than once with different args could effectively improve the design, IMO.

### A couple of other (very) minor things:
- Naming: `Plugin` is a very poor class name :tongue: 
- Boolean arguments are bad (read below)

In the code you linked I saw that `DependencyManager` class (in another repo) [accepts a boolean as constructor argument](https://github.com/brightnucleus/dependencies/blob/master/src/DependencyManager.php#L84). Booleans as flag to switch behavior is not considered a best practice.

Reason is that a code like: `new DependencyManager($config, true);` don't let the reader understand what it means: `true` what?

I myself did this a lot of times, but lately I'm trying to avoid it and use class constants instead.

E.g.: `new DependencyManager($config, DependencyManager::DEFER_ENQUEUE);` is much more clear.

**Comment by GaryJones** [comment]
Thanks.

The Testbed repo is really just a test repo to show how BrightNucleus/config, /shortcodes and /dependencies packages fit and work together. Basically a skeleton that does nothing. I was just interested in your opinion about the structure / `Plugin` part of it.

I know @schlessera will take your comments on board and will address them as needed. Thank you.

**Comment by schlessera** [comment]
@GaryJones, @Giuseppe-Mazzapica You should have told me you're coming to visit, then I would have cleaned up the place a bit... ;)

The `testbed` code was only a quick hack taken from existing code to be able to test my libraries, so it was never meant to be considered as a code quality example yet.

But while we're here, why not make the most out of it.... :)

I'm still experimenting with lots of different structures myself, and I'm not 100% satisfied with any of my former variants, but I've tested enough to have an opinion of my own so far (which goes a long way already in the WP world... ;) ).

I want to share some of my own observations re. your discussion above.

### Main plugin file vs 1 `Plugin` class vs Service Locator pattern

Contrary to @Giuseppe-Mazzapica, I think that the main plugin file (the one in the root folder that contains the metadata) should not contain any real logic at all. Me personally, I consider this a bootstrapping file, one of the many ways of using the system of objects that the plugin provides. Just as you would have a bootstrapping file for testing, and a bootstrapping file for CLI operation, you would have a bootstrapping file for WP plugin usage (Like a "port" in a hexagonal architecture). Amongst other issues, the main plugin file can not be freely defined (needs to have metadata, needs to stay in the root folder) and can not be defined as a proper class file (having just a class definition in there will not work with WP). And the hooking up of classes against WP hooks is something that the classes should take care of themselves. An outside file should not need to know what hook a plugin' different classes will need to be bound to. The objects should be the only ones knowing where they need to be hooked up to. So, most of the time, my main objects contain a `register()` method that will take care of the implementation details of hooking itself up to WP. The bootstrapping file only makes sure that the `register()` method only gets called when it is known that it will be needed.

As to the issue of 1 `Plugin` class (or whatever you want to name it, whether that be the `FrontController`, the `Core`, the `App`, or any other similar object) vs a Service Locator with several service providers, it definitely depends on the complexity of the entire system. However, I will always prefer to have several different services in different WP plugins rather than having everything in 1 single plugin. When building a WP plugin, WP is already the App, and has a system of managing the individual components (even we're not satisfied with that system). My experience has shown me so far that you will not have any benefits of going against that inherent WP structure. You will increase complexity without enjoying many of the benefits you're looking for.

So, I would rather have each "Service Provider" be a single plugin, than have 1 plugin with two dozen "Service Providers" included. Having them in separate plugins will make everything more modular and increase reusability within the WP ecosystem. It also simplifies management from within WP, and allows you to make use of all the tools that are targeted at that structure. It is far from ideal, but neither is having two separate system architectures contained one within the other.

So, I agree that you should not have a God class, but neither should you have a God plugin. I've worked within such a system at a large scale before, and it sucks for many reasons when you want to make larger changes.

How best to wire several plugins together that should cooperate is something I'm still trying to perfect so far, though... ;)

### Let `Plugin` extend Pimple Container

This is a very easy and convenient way of using the "Service Locator" pattern, but comes with some drawbacks. For one, it kills the S in SOLID. But apart from that theoretical issue, it makes it too convenient to abuse the "Service Locator" for all sorts of other stuff. I've seen this be (ab)used for passing config data, setting environment variables, as a DIC container, etc...

If Pimple is used as a "Service Locator" (which it is very good for), it should be clear that that is its only use, and one way of helping to do that is by calling it `ServiceLocator`, instead of `Plugin` or `App`. It should not contain anything but service providers, it should not be used to pass configuration data, and it should be passed around to abuse it as a DI container (which will pass around your entire application from object to object, btw).

I'm still fiddling around with how to best use Pimple in that role. But for the other uses mentioned above, I currently prefer the following approach: I use `Auryn` as the DI container, and I use interfaces in the constructors of my classes. `Auryn` then gets a configuration file that tells it what objects to instantiate for what interfaces, and how it should fill out the other constructor arguments (mainly config files). When I then use `Auryn` to `make()` the top-most object, it does its job recursively, and each object only knows the stuff it needs to know. All dependencies are clear, and everything can be injected differently for unit testing.

As an example, here's a class that needs a `ConfigInterface` as a direct dependency:
<img width="552" alt="screenshot 2016-03-29 17 02 12" src="https://cloud.githubusercontent.com/assets/83631/14112690/04290854-f5d0-11e5-862b-b4f118c1cdd1.png">

`Auryn` will now get a mapping through its configuration of interfaces <=> classes:
<img width="648" alt="screenshot 2016-03-29 17 03 19" src="https://cloud.githubusercontent.com/assets/83631/14112714/280b1370-f5d0-11e5-8c79-816d5fff17f0.png">

The `Config` class however needs some data itself in its constructor:
<img width="400" alt="screenshot 2016-03-29 17 05 07" src="https://cloud.githubusercontent.com/assets/83631/14112779/6a8680ae-f5d0-11e5-9e0e-cebc7f8f36b7.png">

So, we also tell `Auryn` where to fetch the information that it needs for the `$config` argument:
<img width="615" alt="screenshot 2016-03-29 17 06 17" src="https://cloud.githubusercontent.com/assets/83631/14112825/977ac412-f5d0-11e5-9629-888e5cc78270.png">

`Auryn` will then be able to associate specific configuration files (or sub-parts) with specific objects:
<img width="629" alt="screenshot 2016-03-29 17 07 39" src="https://cloud.githubusercontent.com/assets/83631/14112888/d86a141e-f5d0-11e5-8ffe-04e47dd72ded.png">

This system allows us to have 1 single entry point for each major subsystem that we need to `make()` through Auryn, and all the inter-dependencies and configurations will just be taken care of automatically. Each object will explicitly state its dependencies through its constructor, so it is always clear how stuff is coupled together.

### Dangerous `get_instance` param

Yes, I agree, this is one of the areas I still want to improve upon. The current structure has grown organically, and I need to find a different way of doing things.

This should be replaced by either a call to Pimple as the service locator, or a dependency injected through the constructor.

### Naming: Plugin is a very poor class name

Hehe, yes, @GaryJones will confirm that naming is not my forte... :)

### Boolean arguments are bad

Yes, agree, these are better done as constants.
